services:
  db:
    image: postgres:17.4
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=talentHub
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    user: appuser
    secrets:
      - db-password
    environment:
      DB_USER: postgres
      DB_PASSWORD_FILE: /run/secrets/db-password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: talentHub
      DB_SSLMODE: disable
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
secrets:
  db-password:
    file: db/password
