// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/candidato": {
            "get": {
                "description": "Lista Candidatos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidatos"
                ],
                "summary": "Lista Candidatos",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pagination limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de candidatos",
                        "schema": {
                            "$ref": "#/definitions/http.listCandidatoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Mensagem de erro",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create candidato",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidatos"
                ],
                "summary": "Create candidato",
                "parameters": [
                    {
                        "description": "Candidato a ser criado",
                        "name": "candidato",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.candidatoDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Candidato criado",
                        "schema": {
                            "$ref": "#/definitions/http.candidatoDTO"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Mensagem de erro",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/candidato/{id}": {
            "get": {
                "description": "Get Candidato By ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidatos"
                ],
                "summary": "Get Candidato By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Candidato ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Candidato achado",
                        "schema": {
                            "$ref": "#/definitions/http.candidatoDTO"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Mensagem de error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update candidato",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidatos"
                ],
                "summary": "Update candidato",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Candidato ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados de candidatos para atualizar",
                        "name": "candidato",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/talenthub.CandidatoUpdate"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Candidato atualizado",
                        "schema": {
                            "$ref": "#/definitions/http.candidatoDTO"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Mensagem de erro",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vaga": {
            "get": {
                "description": "Lista Vagas",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vagas"
                ],
                "summary": "Lista Vagas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pagination limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de vagas",
                        "schema": {
                            "$ref": "#/definitions/http.listVagaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Mensagem de erro",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create vaga",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vagas"
                ],
                "summary": "Create vaga",
                "parameters": [
                    {
                        "description": "Vaga a ser criada",
                        "name": "candidato",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.createVagaDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Vaga criada",
                        "schema": {
                            "$ref": "#/definitions/http.vagaDTO"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Mensagem de erro",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vaga/close/{id}": {
            "post": {
                "description": "Close vaga",
                "tags": [
                    "Vagas"
                ],
                "summary": "Close vaga",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vaga ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Vaga closed"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Mensagem de erro",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vaga/open/{id}": {
            "post": {
                "description": "Open vaga",
                "tags": [
                    "Vagas"
                ],
                "summary": "Open vaga",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vaga ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Vaga aberta"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Mensagem de erro",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vaga/{id}": {
            "get": {
                "description": "Get Vaga By ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vagas"
                ],
                "summary": "Get Vaga By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vaga ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vaga achada",
                        "schema": {
                            "$ref": "#/definitions/http.vagaDTO"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Mensagem de error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update vaga",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vagas"
                ],
                "summary": "Update vaga",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Vaga ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados de vagas para atualizar",
                        "name": "candidato",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/talenthub.VagaUpdate"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Vaga atualizada",
                        "schema": {
                            "$ref": "#/definitions/http.vagaDTO"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Mensagem de erro",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "http.candidatoDTO": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "education": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.education"
                    }
                },
                "email": {
                    "type": "string"
                },
                "experience": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.experience"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "interests": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "linkedin": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "resume_pdf_path": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "http.createVagaDTO": {
            "type": "object",
            "properties": {
                "area": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "requirements": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "http.education": {
            "type": "object",
            "properties": {
                "course": {
                    "type": "string"
                },
                "education_id": {
                    "type": "integer"
                },
                "institution": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                }
            }
        },
        "http.experience": {
            "type": "object",
            "properties": {
                "company": {
                    "type": "string"
                },
                "experience_id": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "years": {
                    "type": "integer"
                }
            }
        },
        "http.listCandidatoResponse": {
            "type": "object",
            "properties": {
                "candidatos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.candidatoDTO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "http.listVagaResponse": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "vagas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.vagaDTO"
                    }
                }
            }
        },
        "http.vagaDTO": {
            "type": "object",
            "properties": {
                "area": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "location": {
                    "type": "string"
                },
                "posted_date": {
                    "type": "string"
                },
                "requirements": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "talenthub.CandidatoUpdate": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "linkedin": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "resume_pdf_path": {
                    "type": "string"
                }
            }
        },
        "talenthub.VagaUpdate": {
            "type": "object",
            "properties": {
                "area": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "talentHub API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
