// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/candidato": {
            "get": {
                "description": "Lista Candidatos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidatos"
                ],
                "summary": "Lista Candidatos",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pagination limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de candidatos",
                        "schema": {
                            "$ref": "#/definitions/http.listCandidatoResponse"
                        }
                    },
                    "404": {
                        "description": "Mensagem de erro",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update candidato",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidatos"
                ],
                "summary": "Update candidato",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Candidato ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados de candidatos para atualizar",
                        "name": "candidato",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/talenthub.CandidatoUpdate"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Candidato atualizado",
                        "schema": {
                            "$ref": "#/definitions/talenthub.Candidato"
                        }
                    },
                    "404": {
                        "description": "Mensagem de erro",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create candidato",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidatos"
                ],
                "summary": "Create candidato",
                "parameters": [
                    {
                        "description": "Candidato a ser criado",
                        "name": "candidato",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/talenthub.Candidato"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Candidato criado",
                        "schema": {
                            "$ref": "#/definitions/talenthub.Candidato"
                        }
                    },
                    "404": {
                        "description": "Mensagem de erro",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/candidato/{id}": {
            "get": {
                "description": "Get Candidato By ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Candidatos"
                ],
                "summary": "Get Candidato By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Candidato ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Candidato achado",
                        "schema": {
                            "$ref": "#/definitions/talenthub.Candidato"
                        }
                    },
                    "404": {
                        "description": "Mensagem de error",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "http.listCandidatoResponse": {
            "type": "object",
            "properties": {
                "candidatos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/talenthub.Candidato"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "talenthub.Candidato": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "talenthub.CandidatoUpdate": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "talentHub API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
